version: "3"
services:
  nginx:
    image: nginx:1.17-alpine
    ports:
      - 3000:80
    volumes:
      - ./src:/work
      - ./logs:/var/log/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      TZ: ${TZ:-invalid}
    depends_on:
      - app

  app:
    build:
      context: .
      args:
        TZ: ${TZ:-invalid}
    volumes:
      - ./src:/work
      - ./logs:/var/log/php
      - ./php.ini:/usr/local/etc/php/php.ini
      - /work/vendor
    working_dir: /work
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: ${DB_NAME:-invalid}
      DB_USERNAME: ${DB_USER:-invalid}
      DB_PASSWORD: ${DB_PASS:-invalid}
      TZ: ${TZ:-invalid}
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - 13306:3306
    hostname: db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./logs:/var/log/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME:-invalid}
      MYSQL_USER: ${DB_USER:-invalid}
      MYSQL_PASSWORD: ${DB_PASS:-invalid}
      MYSQL_ROOT_PASSWORD: ${DB_PASS:-invalid}
      TZ: ${TZ:-invalid}
